import os

# 项目根目录
PROJECT_DIR = "luodian_backend"

# 需要创建的文件及内容
FILES = {
    ".env.example": (
        "# 应用配置\n"
        "SECRET_KEY=your_super_secret_key_change_me\n"
        "ALGORITHM=HS256\n"
        "ACCESS_TOKEN_EXPIRE_MINUTES=1440\n\n"
        "# 数据库\n"
        "DATABASE_URL=sqlite:///./database.sqlite\n\n"
        "# AI 模型配置\n"
        "AI_PROVIDER=openai\n"
        "OPENAI_API_KEY=sk-xxx\n"
        "OPENAI_BASE_URL=https://api.openai.com/v1\n"
        "ZHIPU_API_KEY=xxx\n"
        "LOCAL_MODEL_URL=http://localhost:8000/generate\n"
    ),
    ".gitignore": (
        "venv/\n__pycache__/\n*.pyc\n.env\ndatabase.sqlite\nuploads/\n.DS_Store\n"
    ),
    "requirements.txt": (
        "fastapi==0.104.1\nuvicorn[standard]==0.24.0\npython-multipart==0.0.6\n"
        "sqlalchemy==2.0.23\npydantic==2.5.0\npydantic-settings==2.1.0\n"
        "python-jose[cryptography]==3.3.0\npasslib[bcrypt]==1.7.4\n"
        "python-dotenv==1.0.0\naiosqlite==0.19.0\nhttpx==0.25.1\n"
    ),
    "README.md": (
        "# 非遗螺钿文化平台 - 后端 API\n\n"
        "## 环境要求\n- Python 3.10+\n- 虚拟环境 (推荐 venv)\n\n"
        "## 安装与运行\n\n"
        "1. 创建虚拟环境\n   ```bash\n   python -m venv venv\n   "
        "source venv/bin/activate   # Linux/Mac\n   venv\\Scripts\\activate      # Windows\n   ```\n"
        "2. 安装依赖\n   ```bash\n   pip install -r requirements.txt\n   ```\n"
        "3. 配置环境变量\n   ```bash\n   cp .env.example .env\n   # 编辑 .env 文件，填入真实密钥\n   ```\n"
        "4. 运行\n   ```bash\n   uvicorn main:app --reload --host 0.0.0.0 --port 3001\n   ```\n"
        "5. 访问 API 文档\n   http://localhost:3001/docs\n\n"
        "## 目录结构\n见项目文件。\n\n"
        "## 主要功能\n- 用户注册/登录/JWT认证\n- 文章增删改查（管理员权限）\n"
        "- 评论与点赞\n- 收藏功能\n- 社区动态（发布、评论、点赞）\n- AI 智能问答（支持 OpenAI/智谱/本地模型）\n\n"
        "## 前端对接\n前端需将 API 请求代理到后端地址，并在请求头添加 `Authorization: Bearer <token>`。\n"
    ),
    "main.py": (
        "from fastapi import FastAPI\n"
        "from fastapi.middleware.cors import CORSMiddleware\n"
        "from contextlib import asynccontextmanager\n\n"
        "from database import engine, Base\n"
        "from routers import user, article, comment, favorite, post, ai\n"
        "from config import settings\n\n"
        "@asynccontextmanager\n"
        "async def lifespan(app: FastAPI):\n"
        "    async with engine.begin() as conn:\n"
        "        await conn.run_sync(Base.metadata.create_all)\n"
        "    yield\n\n"
        "app = FastAPI(title='非遗螺钿文化平台 API', version='1.0.0', lifespan=lifespan)\n\n"
        "app.add_middleware(\n"
        "    CORSMiddleware,\n"
        "    allow_origins=['http://localhost:3000', 'http://127.0.0.1:3000'],\n"
        "    allow_credentials=True,\n"
        "    allow_methods=['*'],\n"
        "    allow_headers=['*'],\n"
        ")\n\n"
        "app.include_router(user.router, prefix='/api/user', tags=['用户'])\n"
        "app.include_router(article.router, prefix='/api/articles', tags=['文章'])\n"
        "app.include_router(comment.router, prefix='/api/comments', tags=['评论'])\n"
        "app.include_router(favorite.router, prefix='/api/favorites', tags=['收藏'])\n"
        "app.include_router(post.router, prefix='/api/posts', tags=['动态'])\n"
        "app.include_router(ai.router, prefix='/api/ai', tags=['AI'])\n\n"
        "@app.get('/')\n"
        "async def root():\n"
        "    return {'message': '螺钿文化平台 API 已启动'}\n"
    ),
    "config.py": (
        "from pydantic_settings import BaseSettings\n\n"
        "class Settings(BaseSettings):\n"
        "    SECRET_KEY: str = 'your_secret_key'\n"
        "    ALGORITHM: str = 'HS256'\n"
        "    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440\n"
        "    DATABASE_URL: str = 'sqlite:///./database.sqlite'\n\n"
        "    AI_PROVIDER: str = 'openai'\n"
        "    OPENAI_API_KEY: str = ''\n"
        "    OPENAI_BASE_URL: str = 'https://api.openai.com/v1'\n"
        "    ZHIPU_API_KEY: str = ''\n"
        "    LOCAL_MODEL_URL: str = 'http://localhost:8000/generate'\n\n"
        "    class Config:\n"
        "        env_file = '.env'\n\n"
        "settings = Settings()\n"
    ),
    "database.py": (
        "from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession\n"
        "from sqlalchemy.orm import sessionmaker, declarative_base\n"
        "from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, func\n"
        "from config import settings\n\n"
        "engine = create_async_engine(\n"
        "    settings.DATABASE_URL.replace('sqlite:///', 'sqlite+aiosqlite:///'),\n"
        "    echo=True\n"
        ")\n"
        "AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)\n\n"
        "Base = declarative_base()\n\n"
        "async def get_db():\n"
        "    async with AsyncSessionLocal() as session:\n"
        "        yield session\n"
    ),
    "models.py": (
        "from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, func, JSON\n"
        "from database import Base\n\n"
        "class User(Base):\n"
        "    __tablename__ = 'users'\n"
        "    id = Column(Integer, primary_key=True, index=True)\n"
        "    username = Column(String(50), unique=True, nullable=False, index=True)\n"
        "    password = Column(String(255), nullable=False)\n"
        "    email = Column(String(100))\n"
        "    bio = Column(String(500))\n"
        "    avatar = Column(String(255))\n"
        "    role = Column(String(20), default='user')\n"
        "    created_at = Column(DateTime, server_default=func.now())\n\n"
        "class Article(Base):\n"
        "    __tablename__ = 'articles'\n"
        "    id = Column(Integer, primary_key=True, index=True)\n"
        "    title = Column(String(200), nullable=False)\n"
        "    content = Column(Text, nullable=False)\n"
        "    category = Column(String(50))\n"
        "    summary = Column(String(500))\n"
        "    cover = Column(String(255))\n"
        "    views = Column(Integer, default=0)\n"
        "    likes = Column(Integer, default=0)\n"
        "    comments_count = Column(Integer, default=0)\n"
        "    created_at = Column(DateTime, server_default=func.now())\n\n"
        "class Comment(Base):\n"
        "    __tablename__ = 'comments'\n"
        "    id = Column(Integer, primary_key=True, index=True)\n"
        "    article_id = Column(Integer, ForeignKey('articles.id', ondelete='CASCADE'))\n"
        "    user_id = Column(Integer, ForeignKey('users.id', ondelete='CASCADE'))\n"
        "    content = Column(Text, nullable=False)\n"
        "    likes = Column(Integer, default=0)\n"
        "    created_at = Column(DateTime, server_default=func.now())\n\n"
        "class Favorite(Base):\n"
        "    __tablename__ = 'favorites'\n"
        "    id = Column(Integer, primary_key=True, index=True)\n"
        "    user_id = Column(Integer, ForeignKey('users.id', ondelete='CASCADE'))\n"
        "    article_id = Column(Integer, ForeignKey('articles.id', ondelete='CASCADE'))\n"
        "    created_at = Column(DateTime, server_default=func.now())\n\n"
        "class Post(Base):\n"
        "    __tablename__ = 'posts'\n"
        "    id = Column(Integer, primary_key=True, index=True)\n"
        "    user_id = Column(Integer, ForeignKey('users.id', ondelete='CASCADE'))\n"
        "    content = Column(Text, nullable=False)\n"
        "    images = Column(JSON)\n"
        "    likes = Column(Integer, default=0)\n"
        "    comments_count = Column(Integer, default=0)\n"
        "    created_at = Column(DateTime, server_default=func.now())\n\n"
        "class PostComment(Base):\n"
        "    __tablename__ = 'post_comments'\n"
        "    id = Column(Integer, primary_key=True, index=True)\n"
        "    post_id = Column(Integer, ForeignKey('posts.id', ondelete='CASCADE'))\n"
        "    user_id = Column(Integer, ForeignKey('users.id', ondelete='CASCADE'))\n"
        "    content = Column(Text, nullable=False)\n"
        "    created_at = Column(DateTime, server_default=func.now())\n"
    ),
    "schemas.py": (
        "from pydantic import BaseModel, EmailStr\n"
        "from datetime import datetime\n"
        "from typing import Optional, List\n\n"
        "class UserCreate(BaseModel):\n"
        "    username: str\n"
        "    password: str\n"
        "    email: Optional[EmailStr] = None\n\n"
        "class UserLogin(BaseModel):\n"
        "    username: str\n"
        "    password: str\n\n"
        "class UserUpdate(BaseModel):\n"
        "    bio: Optional[str] = None\n"
        "    email: Optional[EmailStr] = None\n"
        "    avatar: Optional[str] = None\n\n"
        "class UserOut(BaseModel):\n"
        "    id: int\n"
        "    username: str\n"
        "    email: Optional[str] = None\n"
        "    bio: Optional[str] = None\n"
        "    avatar: Optional[str] = None\n"
        "    role: str\n"
        "    created_at: datetime\n\n"
        "class Token(BaseModel):\n"
        "    access_token: str\n"
        "    token_type: str\n\n"
        "class ArticleCreate(BaseModel):\n"
        "    title: str\n"
        "    content: str\n"
        "    category: Optional[str] = None\n"
        "    summary: Optional[str] = None\n"
        "    cover: Optional[str] = None\n\n"
        "class ArticleUpdate(BaseModel):\n"
        "    title: Optional[str] = None\n"
        "    content: Optional[str] = None\n"
        "    category: Optional[str] = None\n"
        "    summary: Optional[str] = None\n"
        "    cover: Optional[str] = None\n\n"
        "class ArticleOut(BaseModel):\n"
        "    id: int\n"
        "    title: str\n"
        "    content: str\n"
        "    category: Optional[str]\n"
        "    summary: Optional[str]\n"
        "    cover: Optional[str]\n"
        "    views: int\n"
        "    likes: int\n"
        "    comments_count: int\n"
        "    created_at: datetime\n\n"
        "class CommentCreate(BaseModel):\n"
        "    article_id: int\n"
        "    content: str\n\n"
        "class CommentOut(BaseModel):\n"
        "    id: int\n"
        "    article_id: int\n"
        "    user_id: int\n"
        "    content: str\n"
        "    likes: int\n"
        "    created_at: datetime\n"
        "    username: Optional[str] = None\n"
        "    avatar: Optional[str] = None\n\n"
        "class FavoriteCreate(BaseModel):\n"
        "    article_id: int\n\n"
        "class PostCreate(BaseModel):\n"
        "    content: str\n"
        "    images: Optional[List[str]] = None\n\n"
        "class PostOut(BaseModel):\n"
        "    id: int\n"
        "    user_id: int\n"
        "    content: str\n"
        "    images: Optional[List[str]]\n"
        "    likes: int\n"
        "    comments_count: int\n"
        "    created_at: datetime\n"
        "    username: Optional[str] = None\n"
        "    avatar: Optional[str] = None\n\n"
        "class PostCommentCreate(BaseModel):\n"
        "    content: str\n\n"
        "class PostCommentOut(BaseModel):\n"
        "    id: int\n"
        "    user_id: int\n"
        "    content: str\n"
        "    created_at: datetime\n"
        "    username: Optional[str] = None\n"
        "    avatar: Optional[str] = None\n\n"
        "class AIRequest(BaseModel):\n"
        "    message: str\n"
        "    history: Optional[List[dict]] = None\n\n"
        "class AIResponse(BaseModel):\n"
        "    reply: str\n"
    ),
    "auth.py": (
        "from datetime import datetime, timedelta\n"
        "from jose import JWTError, jwt\n"
        "from passlib.context import CryptContext\n"
        "from fastapi import HTTPException, status, Depends\n"
        "from fastapi.security import OAuth2PasswordBearer\n"
        "from sqlalchemy.ext.asyncio import AsyncSession\n"
        "from database import get_db\n"
        "from models import User\n"
        "from sqlalchemy import select\n"
        "from config import settings\n\n"
        "pwd_context = CryptContext(schemes=['bcrypt'], deprecated='auto')\n"
        "oauth2_scheme = OAuth2PasswordBearer(tokenUrl='/api/user/login')\n\n"
        "def verify_password(plain_password, hashed_password):\n"
        "    return pwd_context.verify(plain_password, hashed_password)\n\n"
        "def get_password_hash(password):\n"
        "    return pwd_context.hash(password)\n\n"
        "def create_access_token(data: dict, expires_delta: timedelta = None):\n"
        "    to_encode = data.copy()\n"
        "    if expires_delta:\n"
        "        expire = datetime.utcnow() + expires_delta\n"
        "    else:\n"
        "        expire = datetime.utcnow() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)\n"
        "    to_encode.update({'exp': expire})\n"
        "    encoded_jwt = jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)\n"
        "    return encoded_jwt\n\n"
        "async def get_current_user(token: str = Depends(oauth2_scheme), db: AsyncSession = Depends(get_db)):\n"
        "    credentials_exception = HTTPException(\n"
        "        status_code=status.HTTP_401_UNAUTHORIZED,\n"
        "        detail='Could not validate credentials',\n"
        "        headers={'WWW-Authenticate': 'Bearer'},\n"
        "    )\n"
        "    try:\n"
        "        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])\n"
        "        user_id: int = payload.get('sub')\n"
        "        if user_id is None:\n"
        "            raise credentials_exception\n"
        "    except JWTError:\n"
        "        raise credentials_exception\n"
        "    result = await db.execute(select(User).where(User.id == user_id))\n"
        "    user = result.scalar_one_or_none()\n"
        "    if user is None:\n"
        "        raise credentials_exception\n"
        "    return user\n"
    ),
    "ai_client.py": (
        "import httpx\n"
        "from config import settings\n\n"
        "class AIClient:\n"
        "    def __init__(self):\n"
        "        self.provider = settings.AI_PROVIDER\n\n"
        "    async def chat(self, message: str, history: list = None) -> str:\n"
        "        if self.provider == 'openai':\n"
        "            return await self._openai_chat(message, history)\n"
        "        elif self.provider == 'zhipu':\n"
        "            return await self._zhipu_chat(message, history)\n"
        "        elif self.provider == 'local':\n"
        "            return await self._local_chat(message, history)\n"
        "        else:\n"
        "            return self._mock_reply(message)\n\n"
        "    async def _openai_chat(self, message: str, history: list = None) -> str:\n"
        "        url = f'{settings.OPENAI_BASE_URL}/chat/completions'\n"
        "        headers = {'Authorization': f'Bearer {settings.OPENAI_API_KEY}', 'Content-Type': 'application/json'}\n"
        "        messages = [{'role': 'system', 'content': '你是一个螺钿文化专家，回答关于螺钿的历史、技艺、传承等问题。'}]\n"
        "        if history:\n"
        "            messages.extend(history[-5:])\n"
        "        messages.append({'role': 'user', 'content': message})\n"
        "        payload = {'model': 'gpt-3.5-turbo', 'messages': messages, 'temperature': 0.7}\n"
        "        async with httpx.AsyncClient() as client:\n"
        "            resp = await client.post(url, json=payload, headers=headers, timeout=30)\n"
        "            data = resp.json()\n"
        "            return data['choices'][0]['message']['content']\n\n"
        "    async def _zhipu_chat(self, message: str, history: list = None) -> str:\n"
        "        return '智谱 AI 接口待接入'\n\n"
        "    async def _local_chat(self, message: str, history: list = None) -> str:\n"
        "        url = settings.LOCAL_MODEL_URL\n"
        "        payload = {'prompt': message, 'history': history or []}\n"
        "        async with httpx.AsyncClient() as client:\n"
        "            resp = await client.post(url, json=payload, timeout=60)\n"
        "            data = resp.json()\n"
        "            return data.get('response', '')\n\n"
        "    def _mock_reply(self, message: str) -> str:\n"
        "        keywords = {\n"
        "            '起源': '螺钿技艺起源于商周时期，考古发现表明当时已有贝壳装饰的漆器。',\n"
        "            '点螺': '点螺是螺钿工艺中最精细的技法，将贝壳磨至极薄，切割成细小的点状拼贴。',\n"
        "            '材料': '螺钿主要使用夜光螺、鲍鱼壳、珍珠贝、砗磲等贝壳材料。',\n"
        "        }\n"
        "        for kw, reply in keywords.items():\n"
        "            if kw in message:\n"
        "                return reply\n"
        "        return '关于螺钿的问题，你可以查看知识库或继续问我。'\n\n"
        "ai_client = AIClient()\n"
    ),
    "routers/__init__.py": "# 空文件\n",
    "routers/user.py": (
        "from fastapi import APIRouter, Depends, HTTPException\n"
        "from sqlalchemy.ext.asyncio import AsyncSession\n"
        "from sqlalchemy import select\n"
        "from database import get_db\n"
        "from models import User\n"
        "from schemas import UserCreate, UserLogin, UserUpdate, UserOut, Token\n"
        "from auth import get_password_hash, verify_password, create_access_token, get_current_user\n\n"
        "router = APIRouter()\n\n"
        "@router.post('/register', response_model=Token)\n"
        "async def register(user: UserCreate, db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(select(User).where(User.username == user.username))\n"
        "    if result.scalar_one_or_none():\n"
        "        raise HTTPException(status_code=400, detail='用户名已存在')\n"
        "    hashed = get_password_hash(user.password)\n"
        "    new_user = User(username=user.username, password=hashed, email=user.email, bio='', avatar='')\n"
        "    db.add(new_user)\n"
        "    await db.commit()\n"
        "    await db.refresh(new_user)\n"
        "    access_token = create_access_token(data={'sub': str(new_user.id)})\n"
        "    return Token(access_token=access_token, token_type='bearer')\n\n"
        "@router.post('/login', response_model=Token)\n"
        "async def login(user: UserLogin, db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(select(User).where(User.username == user.username))\n"
        "    db_user = result.scalar_one_or_none()\n"
        "    if not db_user or not verify_password(user.password, db_user.password):\n"
        "        raise HTTPException(status_code=401, detail='用户名或密码错误')\n"
        "    access_token = create_access_token(data={'sub': str(db_user.id)})\n"
        "    return Token(access_token=access_token, token_type='bearer')\n\n"
        "@router.get('/info', response_model=UserOut)\n"
        "async def get_user_info(current_user: User = Depends(get_current_user)):\n"
        "    return current_user\n\n"
        "@router.put('/info', response_model=UserOut)\n"
        "async def update_user_info(update: UserUpdate, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    if update.bio is not None:\n"
        "        current_user.bio = update.bio\n"
        "    if update.email is not None:\n"
        "        current_user.email = update.email\n"
        "    if update.avatar is not None:\n"
        "        current_user.avatar = update.avatar\n"
        "    await db.commit()\n"
        "    await db.refresh(current_user)\n"
        "    return current_user\n"
    ),
    "routers/article.py": (
        "from fastapi import APIRouter, Depends, HTTPException, Query\n"
        "from sqlalchemy.ext.asyncio import AsyncSession\n"
        "from sqlalchemy import select, and_\n"
        "from typing import Optional, List\n"
        "from database import get_db\n"
        "from models import Article, Comment, User\n"
        "from schemas import ArticleCreate, ArticleUpdate, ArticleOut, CommentOut\n"
        "from auth import get_current_user\n\n"
        "router = APIRouter()\n\n"
        "@router.get('/', response_model=List[ArticleOut])\n"
        "async def get_articles(page: int = Query(1, ge=1), limit: int = Query(10, ge=1, le=50), category: Optional[str] = None, keyword: Optional[str] = None, db: AsyncSession = Depends(get_db)):\n"
        "    offset = (page - 1) * limit\n"
        "    conditions = []\n"
        "    if category:\n"
        "        conditions.append(Article.category == category)\n"
        "    if keyword:\n"
        "        conditions.append(Article.title.contains(keyword) | Article.content.contains(keyword))\n"
        "    query = select(Article).where(and_(*conditions)).order_by(Article.created_at.desc()).offset(offset).limit(limit)\n"
        "    result = await db.execute(query)\n"
        "    return result.scalars().all()\n\n"
        "@router.get('/search')\n"
        "async def search_articles(keyword: str = Query(...), db: AsyncSession = Depends(get_db)):\n"
        "    conditions = [Article.title.contains(keyword) | Article.content.contains(keyword)]\n"
        "    query = select(Article).where(and_(*conditions)).order_by(Article.created_at.desc())\n"
        "    result = await db.execute(query)\n"
        "    return result.scalars().all()\n\n"
        "@router.get('/{article_id}', response_model=ArticleOut)\n"
        "async def get_article_detail(article_id: int, db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(select(Article).where(Article.id == article_id))\n"
        "    article = result.scalar_one_or_none()\n"
        "    if not article:\n"
        "        raise HTTPException(status_code=404, detail='文章不存在')\n"
        "    article.views += 1\n"
        "    await db.commit()\n"
        "    await db.refresh(article)\n"
        "    return article\n\n"
        "@router.post('/', response_model=ArticleOut)\n"
        "async def create_article(article: ArticleCreate, current_user = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    if current_user.role != 'admin':\n"
        "        raise HTTPException(status_code=403, detail='无权限')\n"
        "    new_article = Article(**article.dict())\n"
        "    db.add(new_article)\n"
        "    await db.commit()\n"
        "    await db.refresh(new_article)\n"
        "    return new_article\n\n"
        "@router.put('/{article_id}', response_model=ArticleOut)\n"
        "async def update_article(article_id: int, article_update: ArticleUpdate, current_user = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    if current_user.role != 'admin':\n"
        "        raise HTTPException(status_code=403, detail='无权限')\n"
        "    result = await db.execute(select(Article).where(Article.id == article_id))\n"
        "    article = result.scalar_one_or_none()\n"
        "    if not article:\n"
        "        raise HTTPException(status_code=404, detail='文章不存在')\n"
        "    for key, value in article_update.dict(exclude_unset=True).items():\n"
        "        setattr(article, key, value)\n"
        "    await db.commit()\n"
        "    await db.refresh(article)\n"
        "    return article\n\n"
        "@router.delete('/{article_id}')\n"
        "async def delete_article(article_id: int, current_user = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    if current_user.role != 'admin':\n"
        "        raise HTTPException(status_code=403, detail='无权限')\n"
        "    result = await db.execute(select(Article).where(Article.id == article_id))\n"
        "    article = result.scalar_one_or_none()\n"
        "    if not article:\n"
        "        raise HTTPException(status_code=404, detail='文章不存在')\n"
        "    await db.delete(article)\n"
        "    await db.commit()\n"
        "    return {'message': '删除成功'}\n\n"
        "@router.get('/{article_id}/comments', response_model=List[CommentOut])\n"
        "async def get_article_comments(article_id: int, db: AsyncSession = Depends(get_db)):\n"
        "    query = select(Comment, User).join(User, Comment.user_id == User.id).where(Comment.article_id == article_id).order_by(Comment.created_at.desc())\n"
        "    result = await db.execute(query)\n"
        "    comments = []\n"
        "    for comment, user in result:\n"
        "        comments.append(CommentOut(\n"
        "            id=comment.id, article_id=comment.article_id, user_id=comment.user_id,\n"
        "            content=comment.content, likes=comment.likes, created_at=comment.created_at,\n"
        "            username=user.username, avatar=user.avatar\n"
        "        ))\n"
        "    return comments\n"
    ),
    "routers/comment.py": (
        "from fastapi import APIRouter, Depends, HTTPException\n"
        "from sqlalchemy.ext.asyncio import AsyncSession\n"
        "from sqlalchemy import select\n"
        "from database import get_db\n"
        "from models import Comment, Article, User\n"
        "from schemas import CommentCreate, CommentOut\n"
        "from auth import get_current_user\n\n"
        "router = APIRouter()\n\n"
        "@router.post('/', response_model=CommentOut)\n"
        "async def create_comment(comment_data: CommentCreate, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    article_result = await db.execute(select(Article).where(Article.id == comment_data.article_id))\n"
        "    if not article_result.scalar_one_or_none():\n"
        "        raise HTTPException(status_code=404, detail='文章不存在')\n"
        "    new_comment = Comment(article_id=comment_data.article_id, user_id=current_user.id, content=comment_data.content)\n"
        "    db.add(new_comment)\n"
        "    article = article_result.scalar_one()\n"
        "    article.comments_count += 1\n"
        "    await db.commit()\n"
        "    await db.refresh(new_comment)\n"
        "    return CommentOut(\n"
        "        id=new_comment.id, article_id=new_comment.article_id, user_id=new_comment.user_id,\n"
        "        content=new_comment.content, likes=new_comment.likes, created_at=new_comment.created_at,\n"
        "        username=current_user.username, avatar=current_user.avatar\n"
        "    )\n\n"
        "@router.post('/{comment_id}/like')\n"
        "async def like_comment(comment_id: int, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(select(Comment).where(Comment.id == comment_id))\n"
        "    comment = result.scalar_one_or_none()\n"
        "    if not comment:\n"
        "        raise HTTPException(status_code=404, detail='评论不存在')\n"
        "    comment.likes += 1\n"
        "    await db.commit()\n"
        "    return {'message': '点赞成功', 'likes': comment.likes}\n"
    ),
    "routers/favorite.py": (
        "from fastapi import APIRouter, Depends, HTTPException\n"
        "from sqlalchemy.ext.asyncio import AsyncSession\n"
        "from sqlalchemy import select, delete, and_\n"
        "from database import get_db\n"
        "from models import Favorite, Article, User\n"
        "from schemas import FavoriteCreate\n"
        "from auth import get_current_user\n\n"
        "router = APIRouter()\n\n"
        "@router.get('/')\n"
        "async def get_favorites(current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(\n"
        "        select(Favorite, Article)\n"
        "        .join(Article, Favorite.article_id == Article.id)\n"
        "        .where(Favorite.user_id == current_user.id)\n"
        "        .order_by(Favorite.created_at.desc())\n"
        "    )\n"
        "    favorites = []\n"
        "    for fav, article in result:\n"
        "        favorites.append({\n"
        "            'id': fav.id, 'article_id': article.id, 'title': article.title,\n"
        "            'summary': article.summary, 'cover': article.cover, 'created_at': fav.created_at\n"
        "        })\n"
        "    return favorites\n\n"
        "@router.post('/')\n"
        "async def add_favorite(fav: FavoriteCreate, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    article_result = await db.execute(select(Article).where(Article.id == fav.article_id))\n"
        "    if not article_result.scalar_one_or_none():\n"
        "        raise HTTPException(status_code=404, detail='文章不存在')\n"
        "    existing = await db.execute(select(Favorite).where(and_(Favorite.user_id == current_user.id, Favorite.article_id == fav.article_id)))\n"
        "    if existing.scalar_one_or_none():\n"
        "        raise HTTPException(status_code=400, detail='已经收藏过')\n"
        "    new_fav = Favorite(user_id=current_user.id, article_id=fav.article_id)\n"
        "    db.add(new_fav)\n"
        "    await db.commit()\n"
        "    return {'message': '收藏成功'}\n\n"
        "@router.delete('/{article_id}')\n"
        "async def remove_favorite(article_id: int, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(delete(Favorite).where(and_(Favorite.user_id == current_user.id, Favorite.article_id == article_id)))\n"
        "    if result.rowcount == 0:\n"
        "        raise HTTPException(status_code=404, detail='收藏不存在')\n"
        "    await db.commit()\n"
        "    return {'message': '取消收藏成功'}\n"
    ),
    "routers/post.py": (
        "from fastapi import APIRouter, Depends, HTTPException, Query\n"
        "from sqlalchemy.ext.asyncio import AsyncSession\n"
        "from sqlalchemy import select\n"
        "from typing import List\n"
        "from database import get_db\n"
        "from models import Post, PostComment, User\n"
        "from schemas import PostCreate, PostOut, PostCommentCreate, PostCommentOut\n"
        "from auth import get_current_user\n\n"
        "router = APIRouter()\n\n"
        "@router.get('/', response_model=List[PostOut])\n"
        "async def get_posts(page: int = Query(1, ge=1), limit: int = Query(10, ge=1, le=50), db: AsyncSession = Depends(get_db)):\n"
        "    offset = (page - 1) * limit\n"
        "    query = select(Post, User).join(User, Post.user_id == User.id).order_by(Post.created_at.desc()).offset(offset).limit(limit)\n"
        "    result = await db.execute(query)\n"
        "    posts = []\n"
        "    for post, user in result:\n"
        "        posts.append(PostOut(\n"
        "            id=post.id, user_id=post.user_id, content=post.content, images=post.images,\n"
        "            likes=post.likes, comments_count=post.comments_count, created_at=post.created_at,\n"
        "            username=user.username, avatar=user.avatar\n"
        "        ))\n"
        "    return posts\n\n"
        "@router.post('/', response_model=PostOut)\n"
        "async def create_post(post_data: PostCreate, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    new_post = Post(user_id=current_user.id, content=post_data.content, images=post_data.images)\n"
        "    db.add(new_post)\n"
        "    await db.commit()\n"
        "    await db.refresh(new_post)\n"
        "    return PostOut(\n"
        "        id=new_post.id, user_id=new_post.user_id, content=new_post.content, images=new_post.images,\n"
        "        likes=new_post.likes, comments_count=new_post.comments_count, created_at=new_post.created_at,\n"
        "        username=current_user.username, avatar=current_user.avatar\n"
        "    )\n\n"
        "@router.post('/{post_id}/like')\n"
        "async def like_post(post_id: int, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(select(Post).where(Post.id == post_id))\n"
        "    post = result.scalar_one_or_none()\n"
        "    if not post:\n"
        "        raise HTTPException(status_code=404, detail='动态不存在')\n"
        "    post.likes += 1\n"
        "    await db.commit()\n"
        "    return {'message': '点赞成功', 'likes': post.likes}\n\n"
        "@router.get('/{post_id}/comments', response_model=List[PostCommentOut])\n"
        "async def get_post_comments(post_id: int, db: AsyncSession = Depends(get_db)):\n"
        "    result = await db.execute(\n"
        "        select(PostComment, User)\n"
        "        .join(User, PostComment.user_id == User.id)\n"
        "        .where(PostComment.post_id == post_id)\n"
        "        .order_by(PostComment.created_at.desc())\n"
        "    )\n"
        "    comments = []\n"
        "    for comment, user in result:\n"
        "        comments.append(PostCommentOut(\n"
        "            id=comment.id, user_id=comment.user_id, content=comment.content,\n"
        "            created_at=comment.created_at, username=user.username, avatar=user.avatar\n"
        "        ))\n"
        "    return comments\n\n"
        "@router.post('/{post_id}/comments', response_model=PostCommentOut)\n"
        "async def add_post_comment(post_id: int, comment_data: PostCommentCreate, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    post_result = await db.execute(select(Post).where(Post.id == post_id))\n"
        "    post = post_result.scalar_one_or_none()\n"
        "    if not post:\n"
        "        raise HTTPException(status_code=404, detail='动态不存在')\n"
        "    new_comment = PostComment(post_id=post_id, user_id=current_user.id, content=comment_data.content)\n"
        "    db.add(new_comment)\n"
        "    post.comments_count += 1\n"
        "    await db.commit()\n"
        "    await db.refresh(new_comment)\n"
        "    return PostCommentOut(\n"
        "        id=new_comment.id, user_id=new_comment.user_id, content=new_comment.content,\n"
        "        created_at=new_comment.created_at, username=current_user.username, avatar=current_user.avatar\n"
        "    )\n"
    ),
    "routers/ai.py": (
        "from fastapi import APIRouter, Depends, HTTPException\n"
        "from sqlalchemy.ext.asyncio import AsyncSession\n"
        "from database import get_db\n"
        "from schemas import AIRequest, AIResponse\n"
        "from ai_client import ai_client\n"
        "from models import User\n"
        "from auth import get_current_user\n\n"
        "router = APIRouter()\n\n"
        "@router.post('/chat', response_model=AIResponse)\n"
        "async def ai_chat(req: AIRequest, current_user: User = Depends(get_current_user), db: AsyncSession = Depends(get_db)):\n"
        "    try:\n"
        "        reply = await ai_client.chat(req.message, req.history)\n"
        "        return AIResponse(reply=reply)\n"
        "    except Exception as e:\n"
        "        raise HTTPException(status_code=500, detail=f'AI 服务出错: {str(e)}')\n"
    ),
    "utils/__init__.py": "# 空文件\n",
    "utils/logger.py": (
        "import logging\n"
        "import sys\n\n"
        "def setup_logger():\n"
        "    logger = logging.getLogger('luodian')\n"
        "    logger.setLevel(logging.INFO)\n"
        "    handler = logging.StreamHandler(sys.stdout)\n"
        "    handler.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s'))\n"
        "    logger.addHandler(handler)\n"
        "    return logger\n\n"
        "logger = setup_logger()\n"
    ),
}

def create_project():
    # 创建根目录
    os.makedirs(PROJECT_DIR, exist_ok=True)
    # 创建子目录
    os.makedirs(os.path.join(PROJECT_DIR, "routers"), exist_ok=True)
    os.makedirs(os.path.join(PROJECT_DIR, "utils"), exist_ok=True)
    os.makedirs(os.path.join(PROJECT_DIR, "uploads"), exist_ok=True)

    # 写入文件
    for filename, content in FILES.items():
        filepath = os.path.join(PROJECT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Created: {filepath}")

    print("\n✅ 项目生成完成！")
    print(f"进入项目目录: cd {PROJECT_DIR}")
    print("然后运行: pip install -r requirements.txt")
    print("复制 .env.example 为 .env 并编辑配置")
    print("启动服务: uvicorn main:app --reload")

if __name__ == "__main__":
    create_project(),